mr = 0.095;
r = 0.085;
br = 0.001;
mp = 0.024;
Lp = .129;
bp = .00005; 
g = 9.81;
Jr = mr*r*r/3;
Jp = mp*Lp*Lp/3;
l = Lp/2;
Jt = Jr*Jp - (mp*r*l)^2;
disp("non inv pendulum");
a = [0 1 0 0; 0 -Jp*br/Jt ((mp*l)^2)*r*g/Jt mp*r*l*bp/Jt; 0 0 0 1; 0 mp*r*l*br/Jt -Jr*mp*g*l/Jt -Jr*bp/Jt];
b = [0; Jp/Jt; 0; -mp*r*l/Jt];
c = [1 0 0 0; 0 0 1 0];
d = [0; 0];
Co = ctrb(a, b);
unco = length(a) - rank(Co);
disp("uncontrollable states:");
disp(unco);
Ob = obsv(a, c);
unob = length(a) - rank(Ob);
disp("unobserveable states:");
disp(unob);
disp("inv pendulum");
a = [0 1 0 0; 0 -Jp*br/Jt ((mp*l)^2)*r*g/Jt -mp*r*l*bp/Jt; 0 0 0 1; 0 -mp*r*l*br/Jt Jr*mp*g*l/Jt -Jr*bp/Jt];
b = [0; Jp/Jt; 0; mp*r*l/Jt];
c = [1 0 0 0; 0 0 1 0];
d = [0; 0];
Co = ctrb(a, b);
unco = length(a) - rank(Co);
disp("uncontrollable states:");
disp(unco);
Ob = obsv(a, c);
unob = length(a) - rank(Ob);
disp("unobserveable states:");
disp(unob);
disp("both pendulums are controllable and observeable, therefore they are minimal");