mr = 0.095;
r = 0.085;
br = 0.001;
mp = 0.024;
Lp = .129;
bp = .00005; 
g = 9.81;
Jr = mr*r*r/3;
Jp = mp*Lp*Lp/3;
l = Lp/2;
Jt = Jr*Jp - (mp*r*l)^2;
A = [0 1 0 0; 0 -Jp*br/Jt ((mp*l)^2)*r*g/Jt mp*r*l*bp/Jt; 0 0 0 1; 0 mp*r*l*br/Jt -Jr*mp*g*l/Jt -Jr*bp/Jt];
B = [0; Jp/Jt; 0; -mp*r*l/Jt];
A_inv = [0 1 0 0; 0 -Jp*br/Jt -((mp*l)^2)*r*g/Jt -mp*r*l*bp/Jt; 0 0 0 -1; 0 -mp*r*l*br/Jt -Jr*mp*g*l/Jt -Jr*bp/Jt];
B_inv = [0; Jp/Jt; 0; mp*r*l/Jt];
C = [1 0 0 0; 0 0 1 0];
D = [0; 0];
[~,eigval] = eig(A);
[~,eigval_inv] = eig(A_inv);
disp("normal pendulum's eigen values:");
disp(eigval);
disp("an eigenvalue is zero, so we need to check rank(eigval*I-A) =? n-m");
disp("we know n=4, and m=1 (no repeated eig vals), so n-m=3");
disp("normal pendulum's rank(0*I - A):");
disp(rank(-A));
disp("since rank is 3 which is equal to n-m=3, normal pendulum is marginally stable");
disp("inverted pendulum's eigen values:");
disp(eigval_inv);
disp("one of the eigenvalues is >0, so inverted pendulum is unstable");