Ka = 1;
Kt = 20;
M = 5;
B = 10;
Ke = 1;
damp_ratio = 0.8;
Kp = (B^2)/(4*(damp_ratio^2)*Ke*Kt*Ka*M);
sys = tf([Ke*Kt*Ka], [M B 0]);
G = sys;
PM = 60;
wc = 50;
[~, phase_ll] = bode(G, wc);
phi = PM - (phase_ll + 180);
disp(phi);
phi = pi*phi/180;
a = (1+sin(phi))/(1-sin(phi));
t = 1/(sqrt(a)*wc);
disp(a);
disp(t);
LLs = tf([a*t 1], [t 1]);
[mag, ~] = bode(LLs*G, wc);
K = 1/mag;
LLs = K*LLs;
disp(K);
disp(LLs);